from django.contrib import admin
from .models import *
from django.contrib.auth.models import Group

# please note that tha following use case is auto generated By Django Framework 
# this function is connected to use case  001 Create Cafe
# this function is connected to use case  002 Edit cafe
# this function is connected to use case  003 delete cafe
# this function is connected to use case  004 Create Manger
# this function is connected to use case  005  Edit Manger
# this function is connected to use case  006 Delete manager
admin.site.register(Cafe)
admin.site.register(Complaint)
admin.site.register(Order)
admin.site.unregister(Group)





