# Generated by Django 2.2.6 on 2019-10-20 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('location', models.TextField(max_length=400)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='InnoFoodUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('innofooduser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.InnoFoodUser')),
                ('address', models.TextField(max_length=400)),
                ('phone_number', models.TextField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.innofooduser',),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField(max_length=400)),
                ('confirmed', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cafe')),
                ('parameter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.OrderDetail')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('cafe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('visible', models.BooleanField(default=True)),
                ('assigned_cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('complaint_resolved', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cafe')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Order')),
            ],
        ),
    ]
