# Generated by Django 2.2.6 on 2019-11-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191114_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_contact',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
