# Generated by Django 2.2.6 on 2019-10-20 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191020_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='cafe',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cafe', verbose_name='Assigned cafe'),
        ),
    ]
