# Generated by Django 2.2.6 on 2019-11-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_complaint_complaint_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='order',
        ),
    ]
