# Generated by Django 2.2.6 on 2019-10-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191028_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innofooduser',
            name='name',
        ),
        migrations.AddField(
            model_name='innofooduser',
            name='username',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
